### ISSUE TITLE
DHCP server not auto installed (ubutnu 18.04.3)

### ISSUE THREAD

**Issue by iacsvrn** [nabat/AInstall#104]
Install: DHCP
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package isc-dhcp43-server
Pkg:  sudo apt-get -y install  isc-dhcp43-server 1
Result:

True package is isc-dhcp-server.

https://help.ubuntu.com/community/isc-dhcp-server

**Comment by nabat** [comment]
Thank you

Fix it
