### ISSUE TITLE
помилка у функції open

### ISSUE THREAD

**Issue by bublicus** [nabat/AInstall#110]
Fetching https://downloads.sourceforge.net/project/abills/abills/0.95/abills-0.95.05.tgz
tar (child): abills-0.95.05.tgz: помилка у функції open: Немає такого файла або каталогу
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by Yusk03** [comment]
fixed in pull request #111
