### ISSUE TITLE
Autoinstall do not run installation

### ISSUE THREAD

**Issue by denisgolius** [nabat/AInstall#81]
![Screenshot_2019-03-21_11-22-10](https://user-images.githubusercontent.com/5650611/54743030-ef29b900-4bba-11e9-8037-32110c618adc.png)
![Screenshot_2019-03-21_11-22-31](https://user-images.githubusercontent.com/5650611/54743029-ef29b900-4bba-11e9-8aa8-0299a61a54b7.png)

Maybe I missed something ?
Ubuntu 18.04.02

**Comment by andrewkiko** [comment]
Try to run `./install.sh --in_tmux `and show the error if it happends again.

**Comment by horodchukanton** [comment]
Or even **bash +x ./install.sh --in_tmux** to see what have happened before the exit
